title: Home
views:
  - title: Casa
    path: sections
    icon: mdi:home
    type: sections
    max_columns: 1
    sections:
      - type: grid
        cards:
          - type: glance
            show_name: false
            show_icon: true
            show_state: true
            state_color: true
            columns: 4
            entities:
              - entity: sensor.zhimi_mc2_8977_indoor_temperature
              - entity: sensor.zhimi_mc2_8977_relative_humidity
              - entity: sensor.zhimi_mc2_8977_pm25_density
              - entity: binary_sensor.smoke_detector_smoke
            layout_options:
              grid_columns: full

          - type: horizontal-stack
            cards:
              - type: tile
                entity: person.carolmontaes
                name: Carol
                tap_action:
                  action: more-info
              - type: tile
                entity: person.destaben
                name: David
                tap_action:
                  action: more-info
              - type: tile
                entity: automation.alarm
                name: Alarma
                icon: mdi:alarm-light
                tap_action:
                  action: more-info

      - type: grid
        title: Limpieza
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: vacuum.xiaomi_robot_vacuum_x20
                name: Estancias
                show_state: false
                icon: mdi:floor-plan
                icon_height: 34px
                tap_action:
                  action: more-info
              - type: button
                entity: vacuum.xiaomi_robot_vacuum_x20
                name: Casa completa
                show_state: false
                icon: mdi:broom
                icon_height: 34px
                tap_action:
                  action: perform-action
                  perform_action: script.vacuum_clean_all_or_return
                  target: {}

      - type: grid
        title: Estancias
        columns: 2
        cards:
          - type: vertical-stack
            title: Pasillo
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: switch.light
                    show_name: false
                    show_state: true
                    icon: mdi:lightbulb
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: binary_sensor.motion_1_occupancy
                    show_name: false
                    show_state: true
                    icon: mdi:motion-sensor
                    icon_height: 34px
                    tap_action:
                      action: more-info
                  - type: button
                    entity: binary_sensor.door_1_contact
                    show_name: false
                    show_state: true
                    icon: mdi:door
                    icon_height: 34px
                    tap_action:
                      action: more-info

          - type: vertical-stack
            title: Salón
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: switch.smart_plug_1909122087239425186448e1e9039bc1_outlet
                    show_name: false
                    show_state: true
                    icon: mdi:power-plug
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: fan.zhimi_mc2_8977_air_purifier
                    show_name: false
                    show_state: true
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: remote.salon
                    show_name: false
                    show_state: true
                    icon: mdi:television
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: binary_sensor.window_1_contact
                    show_name: false
                    show_state: true
                    icon: mdi:window-closed-variant
                    icon_height: 34px
                    tap_action:
                      action: more-info

          - type: vertical-stack
            title: Dormitorio
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: light.yeelink_color3_6f42_light
                    show_name: false
                    show_state: true
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: remote.bedroom_tv
                    show_name: false
                    show_state: true
                    icon: mdi:television
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: binary_sensor.window_2_contact
                    show_name: false
                    show_state: true
                    icon: mdi:window-closed-variant
                    icon_height: 34px
                    tap_action:
                      action: more-info
                  - type: button
                    entity: media_player.dormitorio
                    show_name: false
                    show_state: true
                    icon_height: 34px
                    tap_action:
                      action: more-info

          - type: vertical-stack
            title: Despacho
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: switch.plug_1
                    show_name: false
                    show_state: true
                    icon: mdi:power-plug
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: media_player.despacho
                    show_name: false
                    show_state: true
                    icon_height: 34px
                    tap_action:
                      action: more-info
                  - type: button
                    entity: switch.plug_2
                    show_name: false
                    show_state: true
                    icon: mdi:printer-3d-nozzle
                    icon_height: 34px
                    tap_action:
                      action: toggle
          - type: vertical-stack
            title: Cocina
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: switch.smart_plug_1909121534757325186448e1e903790b_outlet
                    show_name: false
                    show_state: true
                    icon: mdi:power-plug
                    icon_height: 34px
                    tap_action:
                      action: toggle
                  - type: button
                    entity: binary_sensor.presence_1_presence
                    show_name: false
                    show_state: true
                    icon: mdi:motion-sensor
                    icon_height: 34px
                    tap_action:
                      action: more-info
                  - type: button
                    entity: binary_sensor.window_3_contact
                    show_name: false
                    show_state: true
                    icon: mdi:window-closed-variant
                    icon_height: 34px
                    tap_action:
                      action: more-info
  - title: Limpieza
    path: limpieza
    icon: mdi:robot-vacuum
    type: sections
    max_columns: 2
    sections:
      - type: grid
        title: Aspiradora
        cards:
          - type: custom:xiaomi-vacuum-map-card
            map_source:
              camera: camera.xiaomi_robot_vacuum_x20_map
            calibration_source:
              camera: true
            entity: vacuum.xiaomi_robot_vacuum_x20
            vacuum_platform: Xiaomi Miio
            layout_options:
              grid_columns: full
          - type: tile
            entity: vacuum.xiaomi_robot_vacuum_x20
            name: Aspiradora
            tap_action:
              action: more-info
            layout_options:
              grid_columns: full
  - title: Cámaras
    path: camaras
    icon: mdi:camera
    type: sections
    max_columns: 2
    sections:
      - type: grid
        title: Pasillo y Salón
        cards:
          - type: tile
            entity: camera.tapo_camera_2f13_hd_stream
            name: Ver cámara
            tap_action:
              action: more-info
          - type: horizontal-stack
            cards:
              - type: button
                show_name: false
                show_icon: true
                show_state: false
                icon: mdi:arrow-left
                icon_height: 34px
                tap_action:
                  action: perform-action
                  perform_action: script.move_camera_pasillo
                  target: {}
              - type: button
                show_name: false
                show_icon: true
                show_state: false
                icon: mdi:arrow-right
                icon_height: 34px
                tap_action:
                  action: perform-action
                  perform_action: script.move_camera_salon
                  target: {}

      - type: grid
        title: Despacho
        cards:
          - type: tile
            entity: camera.tapo_camera_3ca0_hd_stream
            name: Ver cámara
            tap_action:
              action: more-info
