- alias: button.short_press
  trigger:
  - device_id: c0ca88e8282bd25e76fc58fefc8bde79
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.bulbs
  mode: single

- alias: button.doble_press
  trigger:
  - device_id: c0ca88e8282bd25e76fc58fefc8bde79
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.smart_plug_1909122087239425186448e1e9039bc1_outlet
  mode: single

- alias: button.long_press
  trigger:
  - device_id: c0ca88e8282bd25e76fc58fefc8bde79
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_1
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.bulbs
  - service: switch.turn_off
    target:
      entity_id:
      - switch.smart_plug_1909122087239425186448e1e9039bc1_outlet
      - switch.smart_plug_1909121534757325186448e1e903790b_outlet
  - service: light.turn_off
    target:
      area_id:
      - bano
  - service: switch.turn_off
    entity_id:
    - switch.p300_smart_plug_1
    - switch.p300_smart_plug_2
    - switch.p300_smart_plug_3
  mode: single
  
- alias: door.opened
  trigger:
  - platform: state
    entity_id: binary_sensor.door_1_opening
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_7_light_6
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_6_light_2
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_5_light
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_4_light_4
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_3_light_3
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_2_light_5
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_1_light_7
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: "Entrada"
  mode: single

- alias: door.closed
  trigger:
  - platform: state
    entity_id: binary_sensor.door_1_opening
    to: 'off'
  condition: []
  action:
  - delay: '00:05:00'
  - service: light.turn_off
    target:
      entity_id: light.bulbs
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: Salon
  mode: single

- alias: entry.motion
  trigger:
  - type: motion
    platform: device
    device_id: 7547ec67cb5e5f8495c31c4fc1f51eb8
    entity_id: f3eb13655589dafcced330306648f60f
    domain: binary_sensor
  condition:
  - condition: time
    after: '07:45:00'
    before: '23:00:00'
  - condition: or
    conditions:
    - condition: device
      device_id: b6b86e085b399c3d131fa172425aa2d3
      domain: device_tracker
      entity_id: 1ee6dfe7bd78c1b1c8bd679e9026d497
      type: is_home
    - condition: device
      device_id: fb9ba01b5a9d368a2993be502db8e24f
      domain: device_tracker
      entity_id: 2c0f2745c4a6403948493efba58d06d1
      type: is_home
  - condition: not
    conditions:
    - condition: state
      entity_id: light.bulbs
      state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_1_light_7
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    target:
      entity_id:
      - light.bulb_2_light_5
  - delay: '00:01:00'
  - condition: not
    conditions:
    - condition: state
      entity_id: binary_sensor.door_1_opening
      state: 'on'
  - service: light.turn_off
    target:
      entity_id: light.bulbs
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: "Entrada"
  mode: single

- alias: bathroom.door_opened
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.contact_sensor_door
    to: "on"
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.bathroom_light
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: Salon
  mode: single

- alias: bathroom.door_closed
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.contact_sensor_door
    to: "on"
  condition: []
  action:
  - delay: '00:05:00'
  - service: light.turn_off
    target:
      entity_id: light.bathroom_light
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: Salon
  mode: single

- alias: home.cleaner
  trigger:
  - platform: time
    at: '10:30:00'
  condition: []
  action:
  - device_id: 4c842285fc57d6d50febe7e6dad40f69
    domain: vacuum
    entity_id: f305d962499595a43cdcba7220422b26
    type: clean
  - service: fan.set_preset_mode
    data:
      preset_mode: Auto
    target:
      entity_id: fan.mi_air_purifier_2h
  - service: switch.turn_off
    entity_id:
    - switch.p300_smart_plug_1
    - switch.p300_smart_plug_2
    - switch.p300_smart_plug_3
  mode: single

- alias: home.empty
  trigger:
    - platform: state
      entity_id: person.destaben
      to: 'not_home'
    - platform: state
      entity_id: person.carolmontaes
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.destaben
        state: 'not_home'
      - condition: state
        entity_id: person.carolmontaes
        state: 'not_home'
  action:
  - service: light.turn_off
    target:
      entity_id: light.bulbs
  - service: switch.turn_off
    entity_id:
    - switch.smart_plug_1909122087239425186448e1e9039bc1_outlet
    - switch.smart_plug_1909121534757325186448e1e903790b_outlet
  - service: light.turn_off
    target:
      area_id:
      - bano
  - service: select.select_option
    target:
      entity_id: select.tapo_camera_2f13_move_to_preset
    data:
      option: "Entrada"
  - service: switch.turn_off
    entity_id:
    - switch.p300_smart_plug_1
    - switch.p300_smart_plug_2
    - switch.p300_smart_plug_3
  mode: single

- alias: night_mode
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: fan.set_preset_mode
    data:
      preset_mode: Silent
    target:
      entity_id: fan.mi_air_purifier_2h
  - service: switch.turn_on
    entity_id:
    - switch.p300_smart_plug_1
    - switch.p300_smart_plug_2
    - switch.p300_smart_plug_3
  mode: single

- alias: turn_on.heater
  trigger:
  - platform: time
    at: '08:00:00'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.smart_plug_1909121534757325186448e1e903790b_outlet
  mode: single

- alias: turn_off.heater
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.smart_plug_1909121534757325186448e1e903790b_outlet
  mode: single